export const FAMILY_MEMBERS = [
  {
    id: "alex",
    name: "Alex",
    role: "adult" as const,
    avatar: "AL",
    color: "#4A7C59",
    age: 38,
  },
  {
    id: "morgan",
    name: "Morgan",
    role: "adult" as const,
    avatar: "MO",
    color: "#7B5EA7",
    age: 36,
  },
  {
    id: "jamie",
    name: "Jamie",
    role: "child" as const,
    avatar: "JA",
    color: "#E08D3C",
    age: 9,
  },
];

export const DEFAULT_PROFILES: Record<string, object> = {
  alex: {
    memberId: "alex",
    interests: [
      { value: "Hiking and trail running", visibility: "share-exact" },
      { value: "Craft coffee and specialty roasts", visibility: "share-summary" },
      { value: "Architecture and urban design", visibility: "share-exact" },
      { value: "Live jazz and acoustic music", visibility: "ai-only" },
      { value: "Woodworking", visibility: "private" },
    ],
    dislikes: [
      { value: "Crowded tourist spots on weekends", visibility: "ai-only" },
      { value: "Very loud bars or clubs", visibility: "share-summary" },
      { value: "Overly structured group activities", visibility: "private" },
    ],
    curiosityItems: [
      { value: "Pottery wheel throwing", visibility: "ai-only" },
      { value: "Wild mushroom foraging", visibility: "share-exact" },
      { value: "Sourdough bread making", visibility: "share-exact" },
    ],
    foodPreferences: [
      { value: "Japanese cuisine", visibility: "share-exact" },
      { value: "Farm-to-table restaurants", visibility: "share-exact" },
    ],
    allergies: ["Tree nuts"],
    crowdTolerance: "low",
    activityLevel: "medium",
    preferredTimeOfDay: ["morning", "evening"],
    travelTolerance: "regional",
    spendingComfort: "comfortable",
    surpriseComfort: "some-ok",
    accessibilityNeeds: [],
    favorites: ["Riverside trail at sunrise", "Farmers market Saturdays"],
    neverSuggest: ["Escape rooms", "Sports bars"],
    updatedAt: new Date().toISOString(),
  },
  morgan: {
    memberId: "morgan",
    interests: [
      { value: "Ceramics and hand-built pottery", visibility: "share-exact" },
      { value: "Botanical gardens and plant care", visibility: "share-exact" },
      { value: "Independent cinema and documentary film", visibility: "share-summary" },
      { value: "Meditation and restorative yoga", visibility: "ai-only" },
      { value: "Collecting vintage cookbooks", visibility: "private" },
    ],
    dislikes: [
      { value: "High-adrenaline activities", visibility: "ai-only" },
      { value: "Very early morning starts", visibility: "share-summary" },
    ],
    curiosityItems: [
      { value: "Glassblowing", visibility: "share-exact" },
      { value: "Natural dyeing with plants", visibility: "ai-only" },
      { value: "Japanese tea ceremony", visibility: "surprise-ok" },
    ],
    foodPreferences: [
      { value: "Mediterranean cuisine", visibility: "share-exact" },
      { value: "Plant-forward menus", visibility: "share-summary" },
    ],
    allergies: ["Shellfish"],
    crowdTolerance: "low",
    activityLevel: "low",
    preferredTimeOfDay: ["afternoon", "evening"],
    travelTolerance: "regional",
    spendingComfort: "moderate",
    surpriseComfort: "loves-surprises",
    accessibilityNeeds: [],
    favorites: ["Sunday afternoon museum visits", "Quiet evenings with good food"],
    neverSuggest: ["Loud concerts", "Competitive sports events"],
    updatedAt: new Date().toISOString(),
  },
  jamie: {
    memberId: "jamie",
    interests: [
      { value: "Drawing and comics", visibility: "share-exact" },
      { value: "LEGO building", visibility: "share-exact" },
      { value: "Dinosaurs and prehistoric life", visibility: "share-exact" },
      { value: "Swimming", visibility: "share-exact" },
    ],
    dislikes: [
      { value: "Very long car rides over 1 hour", visibility: "share-exact" },
    ],
    curiosityItems: [
      { value: "Volcano science experiments", visibility: "share-exact" },
      { value: "Learning to cook simple meals", visibility: "share-exact" },
    ],
    foodPreferences: [
      { value: "Pizza", visibility: "share-exact" },
      { value: "Fresh fruit", visibility: "share-exact" },
    ],
    allergies: [],
    crowdTolerance: "medium",
    activityLevel: "high",
    preferredTimeOfDay: ["morning", "afternoon"],
    travelTolerance: "local",
    spendingComfort: "budget",
    surpriseComfort: "loves-surprises",
    accessibilityNeeds: [],
    favorites: ["Natural history museum", "Backyard s'mores nights"],
    neverSuggest: ["Scary haunted houses"],
    updatedAt: new Date().toISOString(),
  },
};
