export type ExperienceData = {
  id: string;
  title: string;
  description: string;
  imageUrl: string;
  participants: string[];
  participantIds: string[];
  timeframes: string[];
  durationMinutes: number;
  costEstimate: number;
  costBreakdown: string | null;
  energyLevel: "low" | "medium" | "high";
  setting: "home" | "indoor" | "outdoor" | "any";
  planningEffort: "none" | "minimal" | "moderate" | "significant";
  needsChildcare: boolean;
  needsReservation: boolean;
  weatherConsideration: string | null;
  accessibilityNotes: string | null;
  isSaved: boolean;
  isHidden: boolean;
  isShortlisted: boolean;
  whyItFits: string;
  privacySafeSource: string;
  demoDataNote: string;
  distanceMiles: number | null;
  travelTimeMinutes: number | null;
  crowdLevel: string | null;
  surpriseEligible: boolean;
  category: string;
  tags: string[];
  demoAvailability: string | null;
};

export const BASE_EXPERIENCES: ExperienceData[] = [
  {
    id: "exp-001",
    title: "Evening Unwinding — Couch, Candles, and Conversation",
    description:
      "A deliberately slow evening at home. Make a simple charcuterie board, light a few candles, and give yourselves permission to talk without an agenda. No screens, no to-do lists. This works especially well after a long week when the last thing either of you needs is another errand.",
    imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    participants: ["Alex", "Morgan"],
    participantIds: ["alex", "morgan"],
    timeframes: ["right-now", "this-week"],
    durationMinutes: 120,
    costEstimate: 18,
    costBreakdown: "Cheese and crackers ~$12, wine or sparkling water ~$6",
    energyLevel: "low",
    setting: "home",
    planningEffort: "minimal",
    needsChildcare: false,
    needsReservation: false,
    weatherConsideration: null,
    accessibilityNotes: null,
    isSaved: false,
    isHidden: false,
    isShortlisted: false,
    whyItFits: "Both of you have expressed a preference for low-key reconnecting when energy is low. No crowds, no logistics — just a quiet evening together.",
    privacySafeSource: "Matches approved quiet-evening preferences for both adults.",
    demoDataNote: "Demo experience — home activity, no external data.",
    distanceMiles: 0,
    travelTimeMinutes: 0,
    crowdLevel: "none",
    surpriseEligible: true,
    category: "Reconnect",
    tags: ["home", "quiet", "low-energy", "couple", "free", "no-childcare"],
    demoAvailability: "Any evening",
  },
  {
    id: "exp-002",
    title: "Riverside Pottery Class",
    description:
      "A two-hour wheel-throwing session at Kiln & Co., a small ceramics studio in the Riverside Arts District. Instructor-led, no experience needed. You each leave with a piece to take home (after it's fired — they'll contact you in two weeks). Saturday morning sessions run at 10am and are typically quiet with 6–8 participants.",
    imageUrl: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80",
    participants: ["Alex", "Morgan"],
    participantIds: ["alex", "morgan"],
    timeframes: ["this-weekend", "this-month"],
    durationMinutes: 120,
    costEstimate: 95,
    costBreakdown: "Class fee $75 (two people), materials included. Optional: coffee before at nearby café ~$10–12.",
    energyLevel: "low",
    setting: "indoor",
    planningEffort: "moderate",
    needsChildcare: true,
    needsReservation: true,
    weatherConsideration: null,
    accessibilityNotes: "Seated at the wheel. Comfortable clothes recommended — clay gets messy.",
    isSaved: false,
    isHidden: false,
    isShortlisted: false,
    whyItFits: "Pottery was mentioned as something both of you are curious about. Small group, low noise, creative and hands-on. Morning timing works well.",
    privacySafeSource: "This experience aligns with expressed curiosity from both adults about trying something creative together.",
    demoDataNote: "Demo data — event details are illustrative. Verify with studio before booking.",
    distanceMiles: 4.2,
    travelTimeMinutes: 14,
    crowdLevel: "low",
    surpriseEligible: true,
    category: "Creative",
    tags: ["pottery", "creative", "couple", "indoor", "morning", "low-crowd", "childcare-needed", "reservation"],
    demoAvailability: "Saturdays 10am, 1pm — demo availability as of June 2026. Verify before booking.",
  },
  {
    id: "exp-003",
    title: "Friday Night Homemade Pasta",
    description:
      "Make fresh pasta together from scratch — just flour, eggs, and a rolling pin. Pick a sauce to build alongside it, open a bottle of something nice, and turn the kitchen into the restaurant. Takes about an hour of cooking time and zero dollars beyond groceries you likely already have.",
    imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    participants: ["Alex", "Morgan"],
    participantIds: ["alex", "morgan"],
    timeframes: ["this-week", "this-weekend"],
    durationMinutes: 150,
    costEstimate: 22,
    costBreakdown: "Groceries ~$14, wine ~$8. Pasta roller if you don't have one: $24 one-time.",
    energyLevel: "low",
    setting: "home",
    planningEffort: "minimal",
    needsChildcare: false,
    needsReservation: false,
    weatherConsideration: null,
    accessibilityNotes: null,
    isSaved: false,
    isHidden: false,
    isShortlisted: false,
    whyItFits: "Inexpensive, at-home, and collaborative. No babysitter needed if Jamie is asleep. Cooking together tends to generate good conversation.",
    privacySafeSource: "Matches a preference for home-based creative activities with food at the center.",
    demoDataNote: "Home activity — no external booking required.",
    distanceMiles: 0,
    travelTimeMinutes: 0,
    crowdLevel: "none",
    surpriseEligible: false,
    category: "Home Date",
    tags: ["home", "cooking", "couple", "low-cost", "low-energy", "evening"],
    demoAvailability: "Any Friday or Saturday evening",
  },
  {
    id: "exp-004",
    title: "Sunday Morning Trail — Father and Son",
    description:
      "The Cedar Ridge Loop at Millhaven Nature Reserve is a 3.2-mile trail rated easy-to-moderate. The section along the creek is particularly good for spotting wildlife with a 9-year-old — frogs, herons, and the occasional deer. Pack snacks and give yourself 90–120 minutes. The parking lot is rarely full before 8:30am.",
    imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80",
    participants: ["Alex", "Jamie"],
    participantIds: ["alex", "jamie"],
    timeframes: ["this-weekend", "this-month"],
    durationMinutes: 150,
    costEstimate: 12,
    costBreakdown: "Parking $5, trail snacks ~$7. No admission fee.",
    energyLevel: "medium",
    setting: "outdoor",
    planningEffort: "minimal",
    needsChildcare: false,
    needsReservation: false,
    weatherConsideration: "Best on dry mornings. Check 48-hour forecast. Trail can be muddy after rain.",
    accessibilityNotes: "Natural trail surface — not suitable for wheelchairs.",
    isSaved: false,
    isHidden: false,
    isShortlisted: false,
    whyItFits: "Jamie loves being outdoors and active. Alex enjoys trail time in the mornings. Cedar Ridge has enough wildlife for a 9-year-old to stay genuinely interested.",
    privacySafeSource: "Matches outdoor and morning activity preferences, and age-appropriate adventure level.",
    demoDataNote: "Demo location — trail details are illustrative. Verify current conditions before visiting.",
    distanceMiles: 11,
    travelTimeMinutes: 22,
    crowdLevel: "low",
    surpriseEligible: false,
    category: "Outdoors",
    tags: ["hiking", "father-child", "outdoors", "morning", "low-cost", "nature", "sunday"],
    demoAvailability: "Open daily sunrise to sunset — demo data as of June 2026.",
  },
  {
    id: "exp-005",
    title: "Botanical Garden Afternoon — Morgan and Jamie",
    description:
      "The Hartwell Conservatory's Living Lab is designed for young visitors — there's a hands-on section where kids can touch succulents, sketch plants, and explore the butterfly house. Morgan can wander the permanent collections while Jamie works through the junior naturalist activity booklet (included with admission). Quiet on weekday afternoons.",
    imageUrl: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=800&q=80",
    participants: ["Morgan", "Jamie"],
    participantIds: ["morgan", "jamie"],
    timeframes: ["this-week", "this-weekend", "this-month"],
    durationMinutes: 150,
    costEstimate: 28,
    costBreakdown: "Adult $14, child $9, booklet included. Café on-site (~$5–8 optional).",
    energyLevel: "low",
    setting: "indoor",
    planningEffort: "minimal",
    needsChildcare: false,
    needsReservation: false,
    weatherConsideration: null,
    accessibilityNotes: "Fully accessible — stroller and wheelchair friendly throughout.",
    isSaved: false,
    isHidden: false,
    isShortlisted: false,
    whyItFits: "Morgan loves botanical spaces and plant life. Jamie engages well with interactive natural history content. Works any afternoon without advance booking.",
    privacySafeSource: "Aligns with interest in botanical environments and child-friendly educational settings.",
    demoDataNote: "Demo event data — verify hours and current exhibitions with the conservatory.",
    distanceMiles: 6.8,
    travelTimeMinutes: 18,
    crowdLevel: "low",
    surpriseEligible: false,
    category: "Nature & Learning",
    tags: ["botanical", "mother-child", "indoor", "educational", "low-crowd", "afternoon"],
    demoAvailability: "Tues–Sun 10am–5pm — demo data as of June 2026.",
  },
  {
    id: "exp-006",
    title: "Autumn Apple Picking at Orchard Hill Farm",
    description:
      "Orchard Hill is a 45-minute drive out of the city — open for U-pick apples from mid-September through October. The farm also has a cider press, a small petting area (goats, mostly), and a baked goods stand that usually runs out of apple fritters by noon. Bring a jacket — mornings out there are noticeably cooler than the city.",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    participants: ["Alex", "Morgan", "Jamie"],
    participantIds: ["alex", "morgan", "jamie"],
    timeframes: ["this-season", "this-month"],
    durationMinutes: 240,
    costEstimate: 65,
    costBreakdown: "Entry $8/adult, $5/child, ~$35 in apples (half a bushel), cider and snacks ~$15.",
    energyLevel: "medium",
    setting: "outdoor",
    planningEffort: "minimal",
    needsChildcare: false,
    needsReservation: false,
    weatherConsideration: "Best on crisp, dry autumn days. The farm stays open in light rain but muddy paths make it less pleasant.",
    accessibilityNotes: "Unpaved paths. Flat terrain mostly, but not accessible for wheelchairs.",
    isSaved: false,
    isHidden: false,
    isShortlisted: false,
    whyItFits: "A whole-family autumn outing with something for everyone — Jamie and the animals, Morgan and the landscape, Alex and the excuse to be outdoors on a seasonal morning.",
    privacySafeSource: "A seasonal activity that works for all three participants and matches outdoor activity preferences.",
    demoDataNote: "Demo seasonal activity — verify farm hours and U-pick availability each season.",
    distanceMiles: 28,
    travelTimeMinutes: 45,
    crowdLevel: "medium",
    surpriseEligible: false,
    category: "Seasonal",
    tags: ["family", "seasonal", "autumn", "outdoors", "farm", "whole-family"],
    demoAvailability: "Mid-September through October — demo data as of June 2026.",
  },
  {
    id: "exp-007",
    title: "Solo Recharge: Early Morning Walk and Slow Coffee",
    description:
      "A personal recharge window designed for one. Leave before anyone else is awake, walk a familiar route without headphones or a destination, and end at a quiet café for a long, unhurried coffee and something to read. No agenda, no timeline. Typically 90 minutes total.",
    imageUrl: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&q=80",
    participants: ["Alex"],
    participantIds: ["alex"],
    timeframes: ["right-now", "this-week"],
    durationMinutes: 90,
    costEstimate: 8,
    costBreakdown: "Coffee and pastry ~$7–9.",
    energyLevel: "low",
    setting: "outdoor",
    planningEffort: "none",
    needsChildcare: false,
    needsReservation: false,
    weatherConsideration: "Best on clear mornings. Bring a layer — early mornings can be cool.",
    accessibilityNotes: null,
    isSaved: false,
    isHidden: false,
    isShortlisted: false,
    whyItFits: "Individual recharge time matters for sustainable energy at home. A solo early walk is low-overhead, free of logistics, and returns you feeling genuinely reset.",
    privacySafeSource: "Reflects a preference for morning solitude and specialty coffee as a restorative activity.",
    demoDataNote: "Solo activity — no booking or external data needed.",
    distanceMiles: 1.5,
    travelTimeMinutes: 5,
    crowdLevel: "none",
    surpriseEligible: false,
    category: "Recharge",
    tags: ["solo", "morning", "recharge", "low-cost", "low-energy", "walking"],
    demoAvailability: "Any morning",
  },
  {
    id: "exp-008",
    title: "Arthouse Cinema Double Feature",
    description:
      "The Meridian Theater runs weekend double features from their archive — this month it's two Japanese films from the 1970s. Reserved seating, no assigned previews, and the theater holds about 60 people, so it never feels packed. They serve decent wine and local snacks at the bar. Evening shows run at 6pm and 8:15pm.",
    imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80",
    participants: ["Alex", "Morgan"],
    participantIds: ["alex", "morgan"],
    timeframes: ["this-weekend", "this-month"],
    durationMinutes: 300,
    costEstimate: 58,
    costBreakdown: "Two tickets $18 each, wine and snacks ~$20. Parking free on street after 6pm.",
    energyLevel: "low",
    setting: "indoor",
    planningEffort: "minimal",
    needsChildcare: true,
    needsReservation: true,
    weatherConsideration: null,
    accessibilityNotes: "Accessible seating available. Contact theater for specific arrangements.",
    isSaved: false,
    isHidden: false,
    isShortlisted: false,
    whyItFits: "A quiet venue, low crowd, and an interest in independent and international cinema make this a natural match. Evening timing, reserved seats, no rushing.",
    privacySafeSource: "Aligns with interest in independent cinema and a preference for low-crowd evening outings.",
    demoDataNote: "Demo event data — verify current schedule at the Meridian Theater before booking.",
    distanceMiles: 5.1,
    travelTimeMinutes: 15,
    crowdLevel: "low",
    surpriseEligible: true,
    category: "Arts & Culture",
    tags: ["cinema", "couple", "evening", "indoor", "low-crowd", "childcare-needed", "reservation"],
    demoAvailability: "Friday & Saturday evenings — demo data as of June 2026.",
  },
  {
    id: "exp-009",
    title: "Kayaking the Millhaven River Loop",
    description:
      "A 6-mile river loop starting at Millhaven Launch — suitable for beginners but with enough current to feel like a genuine adventure. Rental kayaks are available on-site. The upper section has a small cascade section with light rapids (Class I). Typically takes 2.5–3.5 hours depending on pace. Lifejackets included.",
    imageUrl: "https://images.unsplash.com/photo-1499339525766-3f08a8424e85?w=800&q=80",
    participants: ["Alex", "Morgan", "Jamie"],
    participantIds: ["alex", "morgan", "jamie"],
    timeframes: ["this-season", "this-month", "this-weekend"],
    durationMinutes: 210,
    costEstimate: 105,
    costBreakdown: "Kayak rentals: $35/adult, $22/child. Launch fee $13. Pack lunch from home.",
    energyLevel: "high",
    setting: "outdoor",
    planningEffort: "moderate",
    needsChildcare: false,
    needsReservation: true,
    weatherConsideration: "Requires clear conditions. Cancelled or modified if storms are forecast within 6 hours.",
    accessibilityNotes: "Requires ability to paddle and swim. Not suitable for non-swimmers without adult supervision.",
    isSaved: false,
    isHidden: false,
    isShortlisted: false,
    whyItFits: "An adventurous option that works for the whole family with Jamie's high energy and Alex's trail preference. Morgan can set pace — route is manageable at any speed.",
    privacySafeSource: "Matches an appetite for outdoor adventure within a reasonable distance from home.",
    demoDataNote: "Demo activity — verify kayak availability and water conditions before booking.",
    distanceMiles: 18,
    travelTimeMinutes: 32,
    crowdLevel: "medium",
    surpriseEligible: false,
    category: "Adventure",
    tags: ["kayaking", "adventure", "whole-family", "outdoor", "high-energy", "reservation", "water"],
    demoAvailability: "Weekends May–September — demo data as of June 2026.",
  },
  {
    id: "exp-010",
    title: "Natural History Museum — Dino Exhibit",
    description:
      "The Northgate Natural History Museum's 'Deep Time' exhibit runs through December and includes a full T. rex skeleton, interactive fossil identification stations, and a 20-minute film on mass extinction events. The museum offers Family Saturdays with drop-in activities for ages 6–12. Less crowded on weekday mornings and Sunday afternoons.",
    imageUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80",
    participants: ["Alex", "Morgan", "Jamie"],
    participantIds: ["alex", "morgan", "jamie"],
    timeframes: ["this-month", "this-season"],
    durationMinutes: 180,
    costEstimate: 52,
    costBreakdown: "Admission: $18/adult, $11/child. Exhibit included. Café on-site (~$10 optional).",
    energyLevel: "medium",
    setting: "indoor",
    planningEffort: "minimal",
    needsChildcare: false,
    needsReservation: false,
    weatherConsideration: null,
    accessibilityNotes: "Fully accessible throughout. Audio guides available.",
    isSaved: false,
    isHidden: false,
    isShortlisted: false,
    whyItFits: "Jamie's stated passion for dinosaurs and prehistoric life makes this an obvious fit. The interactive stations hold attention longer than passive exhibits. Educational and genuinely interesting for adults too.",
    privacySafeSource: "Directly aligns with an expressed interest in dinosaurs and prehistoric life.",
    demoDataNote: "Demo event — verify current exhibitions and hours before visiting.",
    distanceMiles: 8.4,
    travelTimeMinutes: 20,
    crowdLevel: "medium",
    surpriseEligible: false,
    category: "Educational",
    tags: ["museum", "educational", "whole-family", "indoor", "dinosaurs", "science", "child-friendly"],
    demoAvailability: "Open Tues–Sun 9am–5pm. 'Deep Time' exhibit through Dec 2026 — demo data.",
  },
  {
    id: "exp-011",
    title: "Autumn Picnic at the Overlook — Resurfaced Idea",
    description:
      "You saved this idea last fall and it didn't happen. The Millhaven Overlook is a 15-minute drive and offers a view of the valley that's particularly striking when the leaves turn. Pack a thermos of something warm, a blanket, and food you both like. Sunrise or late afternoon gives the best light. Ideally just the two of you.",
    imageUrl: "https://images.unsplash.com/photo-1569975020836-44de93cf20dc?w=800&q=80",
    participants: ["Alex", "Morgan"],
    participantIds: ["alex", "morgan"],
    timeframes: ["this-season", "this-month"],
    durationMinutes: 120,
    costEstimate: 20,
    costBreakdown: "Food and drinks from home ~$15–20. Free parking at the overlook.",
    energyLevel: "low",
    setting: "outdoor",
    planningEffort: "minimal",
    needsChildcare: false,
    needsReservation: false,
    weatherConsideration: "Best on clear autumn days. Overlook is exposed — dress in layers.",
    accessibilityNotes: "Short walk from parking — approximately 200m on gravel path.",
    isSaved: true,
    isHidden: false,
    isShortlisted: false,
    whyItFits: "This idea was saved last autumn and resurfaces now that the season is right again. Simple, low-cost, and quietly romantic without needing a reservation.",
    privacySafeSource: "Resurfaced from a previously saved idea — the season has returned for this one.",
    demoDataNote: "Public outdoor location — no booking needed. Demo data.",
    distanceMiles: 9,
    travelTimeMinutes: 17,
    crowdLevel: "low",
    surpriseEligible: true,
    category: "Seasonal",
    tags: ["picnic", "couple", "outdoor", "autumn", "low-cost", "resurfaced", "seasonal"],
    demoAvailability: "September through November",
  },
  {
    id: "exp-012",
    title: "Tasting Menu at Verdure — Date Night Requiring Planning",
    description:
      "Verdure is a farm-to-table restaurant with a 7-course seasonal tasting menu. Reservations open 30 days in advance and fill quickly on weekends. The experience takes about 3 hours and works best without a time constraint afterward. They can accommodate tree nut allergies with advance notice. A rare, deliberate evening.",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    participants: ["Alex", "Morgan"],
    participantIds: ["alex", "morgan"],
    timeframes: ["this-month", "this-year"],
    durationMinutes: 195,
    costEstimate: 245,
    costBreakdown: "Tasting menu $95/person, optional wine pairing $35/person. Gratuity not included (~18%).",
    energyLevel: "low",
    setting: "indoor",
    planningEffort: "significant",
    needsChildcare: true,
    needsReservation: true,
    weatherConsideration: null,
    accessibilityNotes: "Ground floor, accessible entrance. Alert restaurant to dietary needs at booking.",
    isSaved: false,
    isHidden: false,
    isShortlisted: false,
    whyItFits: "A farm-to-table tasting menu at a place with a reputation for quiet, intimate service. Requires advance planning — reservations, childcare, and dietary notes — but worth it for a special occasion.",
    privacySafeSource: "Aligns with interest in exceptional food experiences and farm-to-table cuisine.",
    demoDataNote: "Demo restaurant data — verify availability and current menu before booking.",
    distanceMiles: 7.3,
    travelTimeMinutes: 19,
    crowdLevel: "low",
    surpriseEligible: true,
    category: "Dining",
    tags: ["restaurant", "couple", "fine-dining", "childcare-needed", "reservation", "evening", "special-occasion"],
    demoAvailability: "Thursday–Saturday evenings. Reservations required — demo data as of June 2026.",
  },
];

export function applyStates(
  experiences: ExperienceData[],
  states: Array<{ experienceId: string; isSaved: boolean; isHidden: boolean; isShortlisted: boolean }>
): ExperienceData[] {
  return experiences.map((exp) => {
    const state = states.find((s) => s.experienceId === exp.id);
    if (!state) return exp;
    return {
      ...exp,
      isSaved: state.isSaved,
      isHidden: state.isHidden,
      isShortlisted: state.isShortlisted,
    };
  });
}
